# Generated by Django 5.2.5 on 2025-08-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_motivo_cancelamento_pedido_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_cancelamento',
            field=models.CharField(choices=[('nenhum', 'Nenhum'), ('solicitado', 'Aguardando confirmação'), ('cancelado', 'Cancelado'), ('recusado', 'Recusado')], default='nenhum', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
