# Generated by Django 5.2.5 on 2025-08-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'produto', 'verbose_name_plural': 'produto'},
        ),
    ]
